"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createApp = createApp;
var express_1 = __importDefault(require("express"));
var cors_1 = __importDefault(require("cors"));
var helmet_1 = __importDefault(require("helmet"));
var morgan_1 = __importDefault(require("morgan"));
var env_1 = require("./config/env");
var error_1 = require("./middleware/error");
var auth_routes_1 = __importDefault(require("./routes/auth.routes"));
var users_routes_1 = __importDefault(require("./routes/users.routes"));
var reports_routes_1 = __importDefault(require("./routes/reports.routes"));
var issues_routes_1 = __importDefault(require("./routes/issues.routes"));
var dashboard_routes_1 = __importDefault(require("./routes/dashboard.routes"));
var notifications_routes_1 = __importDefault(require("./routes/notifications.routes"));
var reviews_routes_1 = __importDefault(require("./routes/reviews.routes"));
var revenue_routes_1 = __importDefault(require("./routes/revenue.routes"));
var bookings_routes_1 = __importDefault(require("./routes/bookings.routes"));
var performance_routes_1 = __importDefault(require("./routes/performance.routes"));
var pdf_routes_1 = __importDefault(require("./routes/pdf.routes"));
var ai_routes_1 = __importDefault(require("./routes/ai.routes"));
var pms_routes_1 = __importDefault(require("./routes/pms.routes"));
var occupancy_routes_1 = __importDefault(require("./routes/occupancy.routes"));
var settings_routes_1 = __importDefault(require("./routes/settings.routes"));
var analytics_routes_1 = __importDefault(require("./routes/analytics.routes"));
var commissions_routes_1 = __importDefault(require("./routes/commissions.routes"));
var occupancy_reports_routes_1 = __importDefault(require("./routes/occupancy-reports.routes"));
function createApp() {
    var app = (0, express_1.default)();
    app.use((0, helmet_1.default)());
    app.use((0, cors_1.default)({ origin: env_1.env.corsOrigin.split(',').map(function (s) { return s.trim(); }), credentials: true }));
    app.use(express_1.default.json({ limit: '2mb' }));
    if (env_1.env.nodeEnv !== 'test') {
        app.use((0, morgan_1.default)('dev'));
    }
    app.get('/api/health', function (_req, res) { return res.json({ status: 'ok', time: new Date().toISOString() }); });
    app.use('/api/auth', auth_routes_1.default);
    app.use('/api/users', users_routes_1.default);
    app.use('/api/reports', reports_routes_1.default);
    app.use('/api/issues', issues_routes_1.default);
    app.use('/api/dashboard', dashboard_routes_1.default);
    app.use('/api/notifications', notifications_routes_1.default);
    app.use('/api/reviews', reviews_routes_1.default);
    app.use('/api/revenue', revenue_routes_1.default);
    app.use('/api/bookings', bookings_routes_1.default);
    app.use('/api/performance', performance_routes_1.default);
    app.use('/api/pdf', pdf_routes_1.default);
    app.use('/api/ai', ai_routes_1.default);
    app.use('/api/pms', pms_routes_1.default);
    app.use('/api/occupancy', occupancy_routes_1.default);
    app.use('/api/settings', settings_routes_1.default);
    app.use('/api/analytics', analytics_routes_1.default);
    app.use('/api/commissions', commissions_routes_1.default);
    app.use('/api/occupancy-reports', occupancy_reports_routes_1.default);
    app.use(error_1.notFoundHandler);
    app.use(error_1.errorHandler);
    return app;
}
