import { useQuery } from '@tanstack/react-query';
import { Sparkles, RefreshCw, TrendingUp, Lightbulb } from 'lucide-react';
import { api, apiError } from '../lib/api';
import { AiInsight } from '../lib/types';
import { PageHeader, LoadingState, ErrorState, Spinner } from '../components/ui';

export default function Insights() {
  const { data, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: ['ai-insights'],
    queryFn: async () => (await api.get<AiInsight>('/ai/insights')).data,
    staleTime: 5 * 60 * 1000,
  });

  return (
    <div>
      <PageHeader
        title="AI Insights"
        subtitle="Automated analysis of operations, revenue and guest sentiment."
        action={
          <button className="btn-secondary" disabled={isFetching} onClick={() => refetch()}>
            {isFetching ? <Spinner className="h-4 w-4" /> : <RefreshCw className="h-4 w-4" />} Refresh
          </button>
        }
      />

      {isLoading && <LoadingState label="Generating insights..." />}
      {error && <ErrorState message={apiError(error)} />}

      {data && (
        <div className="space-y-6">
          <div className="card bg-navy text-white">
            <div className="flex items-start gap-3">
              <div className="rounded-md bg-white/10 p-2">
                <Sparkles className="h-5 w-5 text-gold-light" />
              </div>
              <div>
                <h2 className="text-lg font-semibold">Executive Summary</h2>
                <p className="mt-2 leading-relaxed text-white/85">{data.summary}</p>
                <p className="mt-3 text-xs uppercase tracking-wider text-white/40">Generated by {data.provider}</p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <div className="card">
              <h2 className="flex items-center gap-2 text-lg font-semibold text-navy">
                <TrendingUp className="h-5 w-5 text-gold" /> Key Highlights
              </h2>
              <ul className="mt-4 space-y-3">
                {data.highlights.length === 0 && (
                  <li className="text-sm text-on-surface-variant">No highlights available.</li>
                )}
                {data.highlights.map((h, i) => (
                  <li key={i} className="flex gap-3 rounded-md bg-surface-low px-3 py-2.5 text-sm text-on-surface">
                    <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-navy text-[11px] font-semibold text-white">
                      {i + 1}
                    </span>
                    <span>{h}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="card">
              <h2 className="flex items-center gap-2 text-lg font-semibold text-navy">
                <Lightbulb className="h-5 w-5 text-gold" /> Recommendations
              </h2>
              <ul className="mt-4 space-y-3">
                {data.recommendations.length === 0 && (
                  <li className="text-sm text-on-surface-variant">No recommendations available.</li>
                )}
                {data.recommendations.map((r, i) => (
                  <li
                    key={i}
                    className="flex gap-3 rounded-md border border-gold-light/40 bg-gold-light/10 px-3 py-2.5 text-sm text-on-surface"
                  >
                    <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-gold" />
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
